#ifndef _PE_SYSTOLIC_ARRAY_H_
#define _PE_SYSTOLIC_ARRAY_H_

// design space exploration of three vector sizes: float4, float8 and float16
#define DOT_PROD_VECTOR_SIZE      4
#define DOT_PROD_VECTOR_LEVELS    3

#define ACCUM_SHIFT_REG_SIZE      4
#define C_OUT_SHIFT_REG_SIZE      ACCUM_SHIFT_REG_SIZE

#define SYS_ARRAY_NUM_ROWS        5
#define SYS_ARRAY_NUM_COLS        3

#define ROWS_INTERLEAVED          2
#define COLUMNS_INTERLEAVED       2


#define INTERLEAVED 2
#define MATRIX_A_BLOCK_HEIGHT  (INTERLEAVED * SYS_ARRAY_NUM_ROWS)
#define MATRIX_B_BLOCK_WIDTH   (INTERLEAVED * SYS_ARRAY_NUM_COLS)

#define INTERLEAVED_SQUARED (INTERLEAVED * INTERLEAVED)

#define NR_INTERLEAVED (INTERLEAVED * INTERLEAVED)

#define MAT_A_BLOCK_WIDTH         4
#define MAT_A_BLOCK_HEIGHT        MATRIX_A_BLOCK_HEIGHT
#define MAT_A_BLOCK_SIZE          (MAT_A_BLOCK_HEIGHT * MAT_A_BLOCK_WIDTH)
#define MAT_A_BLOCK_NUM_VECTORS   (MAT_A_BLOCK_SIZE   / DOT_PROD_VECTOR_SIZE)

#define MAT_B_BLOCK_HEIGHT        MATRIX_B_BLOCK_WIDTH
#define MAT_B_BLOCK_WIDTH         (COLUMNS_INTERLEAVED * SYS_ARRAY_NUM_COLS)
#define MAT_B_BLOCK_SIZE          (MAT_B_BLOCK_HEIGHT  * MAT_B_BLOCK_WIDTH)
#define MAT_B_BLOCK_NUM_VECTORS   (MAT_B_BLOCK_SIZE    / DOT_PROD_VECTOR_SIZE)

#define MAT_C_BLOCK_HEIGHT        MAT_A_BLOCK_HEIGHT
#define MAT_C_BLOCK_WIDTH         MAT_B_BLOCK_WIDTH


#endif // _PE_SYSTOLIC_ARRAY_H_

